healthcheck:
  workingText: WORKING

redis:
  host: localhost
  port: 1212
  password: ""
  db: 0
  maxPoolSize: 20

api:
  maxReturnedMembers: 2000
  maxReadBufferSize: 80240

newrelic:
  key: ""

worker:
  expirationCheckInterval: 60s
  expirationLimitPerRun: 1000
